name: Tests

on:
  pull_request:

env:
  FORCE_COLOR: 2
  NODE_COV: 16 # The Node.js version to run coverage on

jobs:
  run:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Workaround for npm installation failure on Node.js 14 and Windows
        if: ${{ startsWith(matrix.node, '14') && startsWith(matrix.os, 'windows') }}
        run: npm install -g npm@8.3

      - name: Install latest npm
        run: npm install -g npm && npm --version

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Jest tests
        run: npm run jest -- --runInBand
        if: "!(startsWith(matrix.os, 'ubuntu') && matrix.node == env.NODE_COV)"

      - name: Run Jest tests with coverage
        run: npm run jest -- --runInBand --coverage
        if: startsWith(matrix.os, 'ubuntu') && matrix.node == env.NODE_COV

      - name: Run Coveralls
        uses: coverallsapp/github-action@1.1.3
        if: startsWith(matrix.os, 'ubuntu') && matrix.node == env.NODE_COV
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          path-to-lcov: "./.coverage/lcov.info"
